export const LOGIN_USER = 'AUTH/LOGIN_USER';
export const REGISTER_USER = 'AUTH/REGISTER_USER';
export const LOGOUT = 'AUTH/LOGOUT';
export const CREATE_POST = 'POST/CREATE_POST';
export const POSTS = 'POST/POSTS';

export const LOGIN_USER_SUCCESS = 'AUTH/LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'AUTH/LOGIN_USER_ERROR';

export const REGISTER_USER_SUCCESS = 'AUTH/REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'AUTH/REGISTER_USER_ERROR';

export const LOGOUT_SUCCESS = 'AUTH/LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'AUTH/LOGOUT_ERROR';

export const CREATE_POST_SUCCESS = 'POST/CREATE_POSTR_SUCCESS';
export const CREATE_POST_ERROR = 'POST/CREATE_POST_ERROR';

export const POSTS_SUCCESS = 'POST/POSTS_SUCCESS';
export const POSTS_ERROR = 'POST/POSTS_ERROR';