export const LOGIN_USER = 'AUTH/LOGIN_USER';
export const REGISTER_USER = 'AUTH/REGISTER_USER';
export const USER = 'AUTH/USER';
export const LOGOUT = 'AUTH/LOGOUT';
export const CREATE_POST = 'POST/CREATE_POST';
export const POST_LIST = 'POST/POST_LIST';

export const LOGIN_USER_SUCCESS = 'AUTH/LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'AUTH/LOGIN_USER_ERROR';

export const REGISTER_USER_SUCCESS = 'AUTH/REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'AUTH/REGISTER_USER_ERROR';

export const LOGOUT_SUCCESS = 'AUTH/LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'AUTH/LOGOUT_ERROR';

export const USER_SUCCESS = 'AUTH/USER_SUCCESS';
export const USER_ERROR = 'AUTH/USER_ERROR';

export const CREATE_POST_SUCCESS = 'POST/CREATE_POSTR_SUCCESS';
export const CREATE_POST_ERROR = 'POST/CREATE_POST_ERROR';

export const POST_LIST_SUCCESS = 'POST/POST_LIST_SUCCESS';
export const POST_LIST_ERROR = 'POST/POST_LIST_ERROR';