export const REGISTER_USER = 'REGISTER_USER';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_LOGOUT = 'REGISTER_LOGOUT';