export const CREATE_COMMENT = 'COMMENT/CREATE_COMMENT';
export const COMMENTS = 'COMMENT/COMMENTS';
export const CLEARE_COMMENTS = 'COMMENT/CLEARE_COMMENTS';
export const LIKE = 'COMMENT/LIKE';
export const UNLIKE = 'COMMENT/UNLIKE';
