export const CREATE_COMMENT = 'COMMENT/CREATE_COMMENT';
export const COMMENTS = 'COMMENT/COMMENTS';
export const CLEARE_COMMENTS = 'COMMENT/CLEARE_COMMENTS';
export const COMMENT_LIKE = 'COMMENT/COMMENT_LIKE';
export const COMMENT_UNLIKE = 'COMMENT/COMMENT_UNLIKE';
