export const LOGIN_USER = 'AUTH/LOGIN_USER';
export const REGISTER_USER = 'AUTH/REGISTER_USER';
export const USER = 'AUTH/USER';
export const LOGOUT = 'AUTH/LOGOUT';
export const USER_UPDATE = 'AUTH/USER_UPDATE';

export const LOGIN_USER_SUCCESS = 'AUTH/LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'AUTH/LOGIN_USER_ERROR';

export const REGISTER_USER_SUCCESS = 'AUTH/REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'AUTH/REGISTER_USER_ERROR';

export const LOGOUT_SUCCESS = 'AUTH/LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'AUTH/LOGOUT_ERROR';

export const USER_SUCCESS = 'AUTH/USER_SUCCESS';
export const USER_ERROR = 'AUTH/USER_ERROR';

export const USER_UPDATE_SUCCESS = 'AUTH/USER_UPDATE_SUCCESS';
export const USER_UPDATE_ERROR = 'AUTH/USER_UPDATE_ERROR';
