export const CREATE_COMMENT = 'COMMENT/CREATE_COMMENT';
export const SUB_COMMENTS = 'COMMENT/SUB_COMMENTS';
export const COMMENTS = 'COMMENT/COMMENTS';

export const SUB_COMMENTS_SUCCESS = 'COMMENT/SUB_COMMENTS_SUCCESS';
export const SUB_COMMENTS_ERROR = 'COMMENT/SUB_COMMENTS_ERROR';

export const COMMENTS_SUCCESS = 'COMMENT/COMMENTS_SUCCESS';
export const COMMENTS_ERROR = 'COMMENT/COMMENTS_ERROR';

export const CREATE_COMMENT_SUCCESS = 'COMMENT/CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_ERROR = 'COMMENT/CREATE_COMMENT_ERROR';
