export const CREATE_POST = 'POST/CREATE_POST';
export const POSTS = 'POST/POSTS';
export const POST = 'POST/POST';
export const MY_POSTS = 'POST/MY_POSTS';

export const CREATE_POST_SUCCESS = 'POST/CREATE_POST_SUCCESS';
export const CREATE_POST_ERROR = 'POST/CREATE_POST_ERROR';

export const POSTS_SUCCESS = 'POST/POSTS_SUCCESS';
export const POSTS_ERROR = 'POST/POSTS_ERROR';

export const MY_POSTS_SUCCESS = 'POST/MY_POSTS_SUCCESS';
export const MY_POSTS_ERROR = 'POST/MY_POSTS_ERROR';

export const POST_SUCCESS = 'POST/POST_SUCCESS';
export const POST_ERROR = 'POST/POST_ERROR';
